server:
  port: 8888

# Eureka Discovery Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka

         
spring:
  cloud:
    gateway:
     discovery:
       locator:
         enabled: true
         lower-case-service-id: true

         
         
# Activacion de endpoints         
management:
     endpoints:
       web:
         exposure:
           include: '*'
     endpoint:
       gateway:
          enabled: true
       health:
         show-details: always